### ISSUE TITLE
Admin Error

### ISSUE THREAD

**Issue by Tempbito** [ImAxel0/RedNodeEditor#1]
getting this even when running as admin
![image](https://github.com/ImAxel0/RedNodeEditor/assets/151805712/976a9106-f325-4214-9435-2960eb8234b8)

**Comment by ImAxel0** [comment]
I honestly have no idea, from what is says it seems you aren't logged as the admin

**Comment by Tempbito** [comment]
I managed to install by spamming running it without selecting run as admin. It asked for permission to run as admin after the third time and it work then. It was one of the weirdest thing ever happen to me in windows 10, still can't figure out what's the problem...

**Comment by Tempbito** [comment]
After checking my antivirus (Avast) logs, it was blocking the install each time and spamming it somehow let one instance escape from it.
